name: Bug report
description: Report a bug
title: "[BUG]:"
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe what happend
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Give a description of how to reproduce the bug. Please walk through them step by step.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Media
      description: If applicable, add screenshots, logs or a video to help explain your problem.
    validations:
      required: false
  - type: dropdown
    id: java-version
    attributes:
      label: Java Version
      description: The version of Java that you are using.
      options:
        - "Java 8"
        - "Java 9"
        - "Java 10"
        - "Java 11"
        - "Java 12"
        - "Java 13"
        - "Java 14"
        - "Java 15"
        - "Java 16"
        - "Java 17"
        - "Java 18"
        - "Java 19"
        - "Java 20"
        - "Java 21"
        - "Java 22"
    validations:
      required: true
  - type: input
    id: server-software
    attributes:
      label: Server Software
      description: The software that you are using to run the server.
      placeholder: "Spigot"
    validations:
      required: true
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: The version of Minecraft that you are using.
      placeholder: "1.18.2"
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: The version of the plugin that you are using.
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Any additional information that you would like to share.
