name: Help request or question
description: Request for help or to ask a question
title: "[HELP]:"
labels: ["Help"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this help request!
  - type: textarea
    id: description
    attributes:
      label: With what do you need help?
      description: A clear and concise description of what you need help with or the question you got
    validations:
      required: true
  - type: dropdown
    id: java-version
    attributes:
      label: Java Version
      description: The version of Java that you are using.
      options:
        - "Java 8"
        - "Java 9"
        - "Java 10"
        - "Java 11"
        - "Java 12"
        - "Java 13"
        - "Java 14"
        - "Java 15"
        - "Java 16"
        - "Java 17"
        - "Java 18"
        - "Java 19"
        - "Java 20"
        - "Java 21"
        - "Java 22"
    validations:
      required: false
  - type: input
    id: server-software
    attributes:
      label: Server Software
      description: The software that you are using to run the server.
      placeholder: "Spigot"
    validations:
      required: false
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: The version of Minecraft that you are using.
      placeholder: "1.18.2"
    validations:
      required: false
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: The version of the plugin that you are using.
    validations:
      required: false
    id: additional-information
    attributes:
      label: Additional Information
      description: Any additional information that you would like to share.
